name: 'Get Latest Branch'
description: 'Get the latest (highest) versioned branch from git and outputs that for use in other actions'
branding:
  icon: 'tag'
  color: 'gray-dark'
inputs:
  fallback:
    description: 'Fallback branch to use when no previous branch can be found'
    required: false
  get_next:
    description: 'Return not the highest version but the next highest version. Works in conjunction with the "current_branch" parameter'
    type: boolean
    default: false
    required: false
  current_branch:
    description: 'Optional parameter for use with "get_next". Specifies the current branch to fetch the next highest version branch if it exists.'
    required: false
  prefix:
    description: 'Prefix to query the branch by'
    required: false
  workingDirectory:
    description: The directory to run this workflow in
    default: ""
    required: false
outputs:
  branch:
    description: 'Highest versioned branch'
  version:
    description: 'Branch version'

runs:
  using: 'node20'
  main: 'main.js'
