name: 'Get Latest Branch'
description: 'Get the latest (highest) versioned branch from git and outputs that for use in other actions'
branding:
  icon: 'tag'
  color: 'gray-dark'
inputs:
  fallback:
    description: 'Fallback branch to use when no previous branch can be found'
    required: false
  limit:
    description: 'Optional (non-inclusive) upper limit version branch. Will only return branches lower in version than this or none'
    required: false
  prefix:
    description: 'Prefix to query the branch by'
    required: false
  workingDirectory:
    description: The directory to run this workflow in
    default: ""
    required: false
outputs:
  branch:
    description: 'Highest versioned branch'
  version:
    description: 'Branch version'

runs:
  using: 'node20'
  main: 'main.js'
